# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "polyidiot"
repo_name: "Arixv-TQFT"
show_authors: False
show_links: False
show_badge: False
max_results: 10

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/TQFT-arxiv-daily.json'
json_gitpage_path: './docs/TQFT-arxiv-daily-web.json'
json_wechat_path: './docs/TQFT-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "TQFT, Topological order, Generalized symmetry": 
        filters: ["TQFT", 
        "Topological Field Theory", 
        "Topological Quantum Field Theory",
        "Topological defect", 
        "Homotopical quantum field theory", 
        "Tube algebra", 
        "Honeycomb Floquet code", 
        "Gravitational anomaly", 
        "Multifusion String-net", 
        "Tutaev-Viro TQFT", 
        "Reshetikhin-Turaev TQFT",
        "Chern-Simons theory", 
        "Topological Order", 
        "Topological Entanglement Entropy", 
        "Toric Code", 
        "Quantum Double Model", 
        "Levin-Wen Model", 
        "Walker-Wang Model",
        "Anyon", 
        "Symmetry-protected Topological Phase",
        "Symmetry-enriched topological Phase",
        "Fractional Statistics", 
        "String-net Model", 
        "TQFT", 
        "Topological Field Theory", 
        "Topological Quantum Field Theory",  
        "Tube algebra",  
        "Levin-Wen string-net",
        "Topological Quantum Computation", 
        "Topological Code",
        "Topological Quantum Error-Correction", 
        "X-cube model", 
        "Haah cubic code", 
        "XZZX surface code",
        "SymTFT", 
        "higher-form symmetry", 
        "fusion category symmetry", 
        "Haagerup fusion category symmetry",
        "Haagerup CFT", 
        "Anyonic chain", 
        "Golden chain",
        "Cluster state model", 
        "Cluster ladder model",
        "Gauging non-invertible symmetry",
        "Gauging symmetry",
        "Orbifold CFT",
        "Subsystem symmetry",
        "Topological defect line"]